apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lwcluster
  region: us-east-1

nodeGroups:
  - name: ng1
    describedCapacity: 1
    instanceType: t2.micro
    ssh:
        publicKeyName: myredhatkey

  - name: ng2
    desiredCapacity: 1
    instanceType: t2.small
    ssh:
        publicKeyName: myredhatkey    
